name: edge_ar_app
description: Minimal Edge-based AR Flutter application
version: 0.1.0
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ar_flutter_plugin: ^0.6.3
  camera: ^0.10.0
  geolocator: ^9.0.2
  barcode_scan2: ^4.2.0
  google_ml_kit: ^0.7.0
  tesseract_ocr: ^1.0.0
  surrealdb: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
