name: edge_ar_app
version: 0.1.0
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ar_flutter_plugin: ^0.6.2
  camera: ^0.10.0+4
  google_mlkit_object_detection: ^0.2.2
  google_mlkit_barcode_scanning: ^0.2.2
  google_mlkit_text_recognition: ^0.2.2
  google_mlkit_face_detection: ^0.2.2
  geolocator: ^9.0.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
