name: ar_edge_ui_app

description: Ein plattform체bergreifendes Flutter-Projekt mit AR-Integration und Kanten-basierter Benutzeroberfl채che.

version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ar_flutter_plugin: ^0.6.2
  camera: ^0.10.0
  geolocator: ^9.0.2
  # Platzhalter f체r SurrealDB Dart Unterst체tzung
  # surrealdb: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
